spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/testing
    driverClassName: com.mysql.jdbc.Driver
    password: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: true

server:
  port: '8082'
